### ISSUE TITLE
On-the-fly encryption + virtual file system

### ISSUE THREAD

**Issue by rraallvv** [rducom/TarCompressCrypt#5]
Is it possible to use TarCompressCrypt as a virtual file system to have on-the-fly encryption/decryption of the files in the container?

Keep up the good work.

**Comment by rducom** [comment]
Sorry for the (very) late answer. No, tcc should be seen as a simple compression / decompression tool.
Linux support is not ready yet (hope to have it soon).
What however could be done later, is run tcc from inside your container (compress file from inside), then download your archive, then extract where you want. But mounting a virtual filesystem from an archive is not in my plans 😄
